# Generated by Django 2.1 on 2018-11-16 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_user', models.CharField(max_length=128)),
                ('pay_way', models.CharField(choices=[('alipay', '支付宝'), ('weixinpay', '微信'), ('cashpay', '现金')], default='支付宝', max_length=64)),
                ('money', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Comment', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('pay_state', models.CharField(choices=[('yes', '已结算'), ('no', '待结算')], default='待结算', max_length=32)),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=256, unique=True)),
                ('create_user', models.CharField(max_length=128)),
                ('permission', models.CharField(choices=[('open', '公开'), ('close', '私密')], default='私密', max_length=32)),
                ('home_states', models.CharField(choices=[('full', '满员'), ('empty', '可入住')], default='满员', max_length=64)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='HomeMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_user', models.CharField(max_length=128)),
                ('leave_word', models.TextField()),
                ('leave_time', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Record.Home')),
            ],
            options={
                'verbose_name': '房间留言',
                'verbose_name_plural': '房间留言',
                'ordering': ['leave_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('tag_name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='home',
            name='roommates',
            field=models.ManyToManyField(to='Record.User'),
        ),
        migrations.AddField(
            model_name='expense',
            name='join_user',
            field=models.ManyToManyField(to='Record.User'),
        ),
    ]
